#!/usr/bin/env python3

import os
import shutil


def mvn_clean_install():
    cwd = os.getcwd()
    os.chdir("java")
    exitcode = os.system('mvn clean install -DskipTests')
    if exitcode != 0:
        print("Failed to build Simulator due to a Maven build failure.")
        exit(exitcode)
    os.chdir(cwd)


def make_empty_dir(dir):
    if os.path.isdir(dir):
        shutil.rmtree(dir)
    os.mkdir(dir)


mvn_clean_install()
make_empty_dir("drivers")

# Copy the drivers.
for driver_dir_name in os.listdir("java/drivers"):
    driver_dir = f"java/drivers/{driver_dir_name}"
    if not os.path.isdir(driver_dir):
        continue
    print(driver_dir)
    os.mkdir(f"drivers/{driver_dir_name}")
    target_dir = f"{driver_dir}/target"
    os.system(f"cp {target_dir}/*.jar drivers/{driver_dir_name}")

    if os.path.isdir(f"{driver_dir}/conf"):
        os.system(f"cp -r {driver_dir}/conf drivers/{driver_dir_name}")

make_empty_dir("lib")
os.system(f"cp java/simulator/target/*.jar lib/")
os.system(f"cp java/extra/* lib/")
os.system(f"rm drivers/driver-hazelcast4plus/hazelcast-*.jar")

os.system(f"rm -fr drivers/driver-hazelcast4")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast4")
os.system(f"rm -fr drivers/driver-hazelcast-enterprise4")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast-enterprise4")

os.system(f"rm -fr drivers/driver-hazelcast5")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast5")
os.system(f"rm -fr drivers/driver-hazelcast-enterprise5")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast-enterprise5")

os.system(f"rm -fr drivers/driver-hazelcast4plus")

