#!/usr/bin/env python3

import os
import shutil


def mvn_clean_install():
    cwd = os.getcwd()
    os.chdir("java")
    exitcode = os.system('mvn clean install -DskipTests')
    if exitcode != 0:
        print("Failed to build Simulator due to a Maven build failure.")
        exit(exitcode)
    os.chdir(cwd)


def make_empty_dir(dir):
    if os.path.isdir(dir):
        shutil.rmtree(dir)
    os.mkdir(dir)


mvn_clean_install()
make_empty_dir("drivers")

# Copy the drivers.
for driver_dir_name in os.listdir("java/drivers"):
    src_driver_dir = f"java/drivers/{driver_dir_name}"
    target_driver_dir = f"drivers/{driver_dir_name}"
    if not os.path.isdir(src_driver_dir):
        continue
    print(src_driver_dir)
    os.mkdir(f"drivers/{driver_dir_name}")
    target_dir = f"{src_driver_dir}/target"
    os.system(f"cp {target_dir}/*.jar drivers/{driver_dir_name}")

    if os.path.isdir(f"{src_driver_dir}/conf"):
        os.system(f"cp -r {src_driver_dir}/conf {target_driver_dir}")

        # Ensure the install script is executable
        if os.path.exists(f"{target_driver_dir}/conf/install"):
            os.system(f"chmod +x {target_driver_dir}/conf/install")

make_empty_dir("lib")
os.system(f"cp java/simulator/target/*.jar lib/")
os.system(f"cp java/extra/* lib/")
os.system(f"rm drivers/driver-hazelcast4plus/hazelcast-*.jar")
os.system(f"rm drivers/driver-hazelcast3/hazelcast-*.jar")

os.system(f"cp -r drivers/driver-hazelcast3 drivers/driver-hazelcast-enterprise3")

os.system(f"rm -fr drivers/driver-hazelcast4")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast4")
os.system(f"rm -fr drivers/driver-hazelcast-enterprise4")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast-enterprise4")

os.system(f"rm -fr drivers/driver-hazelcast5")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast5")
os.system(f"rm -fr drivers/driver-hazelcast-enterprise5")
os.system(f"cp -r drivers/driver-hazelcast4plus drivers/driver-hazelcast-enterprise5")

os.system(f"rm -fr drivers/driver-hazelcast4plus")

