#!/bin/bash

set -e

SIMULATOR_VERSION=$(grep -m 1 "<version>.*</version>" pom.xml | awk -F'[><]' '{print $3}')
if [ -z "${SIMULATOR_VERSION}" ]; then
    SIMULATOR_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[' | grep -vi 'download')
fi
PROJECT_HOME=~
if [ -n "$1" ]; then
    PROJECT_HOME=$1
elif [ -n "${SIMULATOR_HOME}" ]; then
    PROJECT_HOME=$(dirname "${SIMULATOR_HOME}")
fi

echo SIMULATOR_VERSION = ${SIMULATOR_VERSION}

mvn --quiet clean install -DskipTests
SIMULATOR_HOME=${PROJECT_HOME}/hazelcast-simulator-${SIMULATOR_VERSION}
rm -fr ${SIMULATOR_HOME}
unzip -q -d ${PROJECT_HOME} dist/target/hazelcast-simulator-${SIMULATOR_VERSION}-dist.zip
echo "SIMULATOR_HOME=${SIMULATOR_HOME}"