#!/usr/bin/python3

import os
import shutil


def mvn_clean_install():
    cwd = os.getcwd()
    os.chdir("java")
    os.system('mvn clean install -DskipTests')
    os.chdir(cwd)


def empty_dir(dir):
    if os.path.isdir(dir):
        shutil.rmtree(dir)
    os.mkdir(dir)

mvn_clean_install()
empty_dir("drivers")

# Copy the drivers.
for driver_dir_name in os.listdir("java/drivers"):
    driver_dir = f"java/drivers/{driver_dir_name}"
    if not os.path.isdir(driver_dir):
        continue
    print(driver_dir)
    os.mkdir(f"drivers/{driver_dir_name}")
    target_dir = f"{driver_dir}/target"
    os.system(f"cp {target_dir}/*.jar drivers/{driver_dir_name}")

    if os.path.isdir(f"{driver_dir}/conf"):
        os.system(f"cp -r {driver_dir}/conf drivers/{driver_dir_name}")

empty_dir("lib")
os.system(f"cp java/simulator/target/*.jar lib/")
os.system(f"cp java/extra/* lib/")
os.system(f"rm drivers/driver-hazelcast4plus/hazelcast-*.jar")
os.system(f"rm drivers/driver-hazelcast3/hazelcast-*.jar")
