#!/bin/bash

# This script will setup the environment

set -e

inventory apply

echo "Waiting for instances to start"
sleep 60

inventory install java --url https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.9%2B10/OpenJDK21U-jdk_x64_linux_hotspot_21.0.9_10.tar.gz

inventory install simulator
