---
- name: Generate Keystore and Truststore
  hosts: localhost

  vars:
    rsa_key_size: 2048

  tasks:
    - name: Generate keystore
      command:
        chdir: /tmp
        creates: /tmp/simulator-keystore-rsa{{ rsa_key_size }}.jks
        cmd: > 
          keytool -genkeypair -alias member -keyalg RSA -keysize {{ rsa_key_size }} -validity 365 
            -keystore simulator-keystore-rsa{{ rsa_key_size }}.jks -storepass changeit
            -dname "CN=simulator, OU=IT, O=Hazelcast, L=City, C=GB"

    - name: Export cert
      command:
        chdir: /tmp
        creates: /tmp/simulator-member-rsa{{ rsa_key_size }}.crt
        cmd: >
          keytool -export -alias member -keystore simulator-keystore-rsa{{ rsa_key_size }}.jks 
            -file simulator-member-rsa{{ rsa_key_size }}.crt -storepass changeit -rfc

    - name: Generate truststore
      command:
        chdir: /tmp
        creates: /tmp/simulator-truststore-rsa{{ rsa_key_size }}.jks
        cmd: >
          keytool -import -noprompt -alias member -file simulator-member-rsa{{ rsa_key_size }}.crt 
            -keystore simulator-truststore-rsa{{ rsa_key_size }}.jks -storepass changeit

    - name: Finalise keystore
      copy:
        force: true
        src: /tmp/simulator-keystore-rsa{{ rsa_key_size }}.jks
        dest: /tmp/simulator-keystore.jks

    - name: Finalise truststore
      copy:
        force: true
        src: /tmp/simulator-truststore-rsa{{ rsa_key_size }}.jks
        dest: /tmp/simulator-truststore.jks

- name: Copy Keystore and Truststore to remote servers
  hosts: all
  tasks:
    - name: Copy keystore to remote server
      copy:
        src: /tmp/simulator-keystore.jks
        dest: /tmp/keystore.jks
        mode: '0444'
    - name: Copy truststore to remote server
      copy:
        src: /tmp/simulator-truststore.jks
        dest: /tmp/truststore.jks
        mode: '0444'
