---
- name: Generate Keystore and Truststore
  hosts: localhost

  vars:
    rsa_key_size: 2048

  tasks:
    - name: Generate keystore
      command:
        chdir: /tmp
        creates: /tmp/simulator-keystore-rsa{{ rsa_key_size }}.jks
        cmd: > 
          keytool -genkeypair -alias member -keyalg RSA -keysize {{ rsa_key_size }} -validity 365 
            -keystore simulator-keystore-rsa{{ rsa_key_size }}.jks -storepass changeit
            -dname "CN=simulator, OU=IT, O=Hazelcast, L=City, C=GB"

    - name: Export cert
      command:
        chdir: /tmp
        creates: /tmp/simulator-member-rsa{{ rsa_key_size }}.crt
        cmd: >
          keytool -export -alias member -keystore simulator-keystore-rsa{{ rsa_key_size }}.jks 
            -file simulator-member-rsa{{ rsa_key_size }}.crt -storepass changeit -rfc

    - name: Generate truststore
      command:
        chdir: /tmp
        creates: /tmp/simulator-truststore-rsa{{ rsa_key_size }}.jks
        cmd: >
          keytool -import -noprompt -alias member -file simulator-member-rsa{{ rsa_key_size }}.crt 
            -keystore simulator-truststore-rsa{{ rsa_key_size }}.jks -storepass changeit

    - name: Finalise keystore
      copy:
        src: /tmp/simulator-keystore-rsa{{ rsa_key_size }}.jks
        dest: /tmp/simulator-keystore.jks
        force: true

    - name: Finalise truststore
      copy:
        src: /tmp/simulator-truststore-rsa{{ rsa_key_size }}.jks
        dest: /tmp/simulator-truststore.jks
        force: true

    - name: Create openssl private key
      community.crypto.openssl_privatekey:
        path: /tmp/simulator-cert.key
        size: "{{ rsa_key_size }}"

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: /tmp/simulator-cert.key
        common_name: simulator
        organization_name: Hazelcast
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: /tmp/simulator-cert.pem
        csr_content: "{{ csr.csr }}"
        privatekey_path: /tmp/simulator-cert.key
        provider: selfsigned

    - name: Convert private key to PKCS8 format
      community.crypto.openssl_privatekey_convert:
        src_path: /tmp/simulator-cert.key
        dest_path: /tmp/simulator-key.pem
        format: pkcs8

- name: Copy Keystore and Truststore to remote servers
  hosts: all
  tasks:
    - name: Copy jks keystore to remote server
      copy:
        src: /tmp/simulator-keystore.jks
        dest: /tmp/keystore.jks
        force: true
        mode: '0444'

    - name: Copy jks truststore to remote server
      copy:
        src: /tmp/simulator-truststore.jks
        dest: /tmp/truststore.jks
        force: true
        mode: '0444'

    - name: Copy openssl key to remote server
      copy:
        src: /tmp/simulator-key.pem
        dest: /tmp/key.pem
        force: true
        mode: '0444'

    - name: Copy openssl cert to remote server
      copy:
        src: /tmp/simulator-cert.pem
        dest: /tmp/cert.pem
        force: true
        mode: '0444'
